version: "3.7"

services:
    # image project
    curso_api_cache:
        build:
            args:
                user: adson
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www/
        depends_on: 
            - curso_api_cache_redis
            - curso_api_cache_queue
        networks: 
            - laravel
    
    # nginx
    curso_api_cache_nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8181:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel

    # db mysql
    curso_api_cache_mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3388:3306"
        networks: 
            - laravel

    # queue
    curso_api_cache_queue:
        build: 
            args:
                user: adson
                uid: 1000
            context: ./
            dockerfile: Dockerfile    
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - curso_api_cache_redis
        networks: 
            - laravel

    # redis
    curso_api_cache_redis:
        image: redis:latest
        networks: 
            - laravel

networks: 
    laravel:
        driver: bridge